# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(798, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 170, 250, 51))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.IntervalType = QtGui.QLabel(self.verticalLayoutWidget)
        self.IntervalType.setObjectName(_fromUtf8("IntervalType"))
        self.verticalLayout.addWidget(self.IntervalType)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.HourlyFlag = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.HourlyFlag.setObjectName(_fromUtf8("HourlyFlag"))
        self.horizontalLayout.addWidget(self.HourlyFlag)
        self.DailyFlag = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.DailyFlag.setObjectName(_fromUtf8("DailyFlag"))
        self.horizontalLayout.addWidget(self.DailyFlag)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 111, 250, 51))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.DataHistoryType = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.DataHistoryType.setObjectName(_fromUtf8("DataHistoryType"))
        self.verticalLayout_2.addWidget(self.DataHistoryType)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radioButton_3 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.horizontalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_4 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.horizontalLayout_2.addWidget(self.radioButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 300, 219, 54))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.IntervalType_2 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.IntervalType_2.setObjectName(_fromUtf8("IntervalType_2"))
        self.verticalLayout_3.addWidget(self.IntervalType_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.comboBox = QtGui.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(30, 400, 198, 66))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.StartingDate = QtGui.QDateEdit(self.verticalLayoutWidget_4)
        self.StartingDate.setObjectName(_fromUtf8("StartingDate"))
        self.horizontalLayout_4.addWidget(self.StartingDate)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.EndingDate = QtGui.QDateEdit(self.verticalLayoutWidget_4)
        self.EndingDate.setObjectName(_fromUtf8("EndingDate"))
        self.horizontalLayout_5.addWidget(self.EndingDate)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 239, 219, 54))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.IntervalType_3 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.IntervalType_3.setObjectName(_fromUtf8("IntervalType_3"))
        self.verticalLayout_6.addWidget(self.IntervalType_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.comboBox_2 = QtGui.QComboBox(self.verticalLayoutWidget_5)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.comboBox_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuQuery_Engine = QtGui.QMenu(self.menubar)
        self.menuQuery_Engine.setObjectName(_fromUtf8("menuQuery_Engine"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuQuery_Engine.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.radioButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), self.comboBox_2.clearEditText)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.IntervalType.setText(_translate("MainWindow", "Interval Type", None))
        self.HourlyFlag.setText(_translate("MainWindow", "Hourly", None))
        self.DailyFlag.setText(_translate("MainWindow", "Daily", None))
        self.DataHistoryType.setText(_translate("MainWindow", "Data Type", None))
        self.radioButton_3.setText(_translate("MainWindow", "Historical", None))
        self.radioButton_4.setText(_translate("MainWindow", "Recent", None))
        self.IntervalType_2.setText(_translate("MainWindow", "Stations", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "All", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Berlin", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "Hamburg", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "Munich", None))
        self.label.setText(_translate("MainWindow", "Starting Date", None))
        self.label_2.setText(_translate("MainWindow", "Ending Date", None))
        self.IntervalType_3.setText(_translate("MainWindow", "Parameters", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "All", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Berlin", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Hamburg", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Munich", None))
        self.menuQuery_Engine.setTitle(_translate("MainWindow", "Query Engine", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

